### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by misode** [misode/loot-table#1]
**Missing Features**
- [x] `damage_source_properties` condition
- [x] `table_bonus` condition
- [x] `enchantments` item parameter
- [x] `effects` entity parameter
- [x] `distance` entity parameter

**Comment by misode** [comment]
All features added in #15
